version: "3"

services:
  bitcoind:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.bitcoin
      args:
        VERSION: "22.0"
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_RPC_AUTH: johndoe:75669617aaedb394397ddc7213bb1ea9$$3a50ee2f4dff3cd49475295124aa3d48a61d6ae3cdcb4d2cf199dac6551217f4
    user: root:root
    entrypoint: [ "bitcoind" ]
    command:
      - -datadir=/data
      - -wallet=cashcow
      - -regtest
      - -rpcauth=johndoe:75669617aaedb394397ddc7213bb1ea9$$3a50ee2f4dff3cd49475295124aa3d48a61d6ae3cdcb4d2cf199dac6551217f4
      - -rpcport=43782
      - -rpcbind=0.0.0.0:43782
      - -rpcallowip=0.0.0.0/0
      - -port=39388
      - -txindex=1
      - -zmqpubrawblock=tcp://0.0.0.0:28332
      - -zmqpubrawtx=tcp://0.0.0.0:28333
      - -zmqpubsequence=tcp://0.0.0.0:28335
      - -deprecatedrpc=signrawtransaction
      - -assumevalid=00000000000000000012d0c0982d818aa909d78e54525b10563c698d89997632
      - -maxmempool=10 # MB
      - -fallbackfee=0.0001
    expose:
      - "43782" # RPC
      - "39388" # P2P
      - "28332" # ZMQ
      - "28333" # ZMQ
      - "28335" # ZMQ
    ports:
      - "43782:43782" # RPC
      - "28332:28332"
      - "28333:28333"
      - "28335:28335"
    volumes:
      - "./data/bitcoin:/data"

  lightningd:
    restart: unless-stopped
    build:
      context: .
      args:
        LIGHTNINGD_VERSION: "v0.10.1"
    environment:
      EXPOSE_TCP: "true"
      LIGHTNINGD_NETWORK: regtest
      LIGHTNINGD_CHAIN: btc
      LIGHTNINGD_PORT: 9735
      LIGHTNINGD_ANNOUNCEADDR: lightningd
      LIGHTNINGD_DATA: /root/.lightning
    command:
      - "--network=regtest"
      - "--lightning-dir=/root/.lightning"
      - "--allow-deprecated-apis=false"
      - "--bitcoin-datadir=/deps/.bitcoin"
      - "--bitcoin-rpcuser=johndoe"
      - "--bitcoin-rpcpassword=unsafepassword"
      - "--bitcoin-rpcconnect=bitcoind"
      - "--bitcoin-rpcport=43782"
      # - "--plugin-dir=/plugins"
      # - "--plugin=/root/.lightning/plugins/summary"
      # - "--plugin=/opt/lightningd/plugins/summary"
    depends_on:
      - bitcoind
    volumes:
      - "lightningd:/root/.lightning"
      - "./data/bitcoin:/deps/.bitcoin"
    expose:
      - "9735"

volumes:
  lightningd:
